### ISSUE TITLE
"No 'stacktrace.app.packages' was configured" Error

### ISSUE THREAD

**Issue by SpringGrim** [egg82/AltFinder#4]
I get this error in the console with default configs.
Java 8, Spigot 1.13.2

[WARNING] [AltFinder] {i.s.DefaultSentryClientFactory} No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames

[WARNING] [AltFinder] {i.s.DefaultSentryClientFactory} No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames

[WARNING] [AltFinder] {i.s.DefaultSentryClientFactory} No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames

[WARNING] [AltFinder] {i.s.DefaultSentryClientFactory} No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames

**Comment by egg82** [comment]
This may be an issue with an old dependency. Give the latest (test) build a shot at https://jenkins.egg82.me/job/egg82/job/AntiVPN/job/fix%252F%252315/

**Comment by egg82** [comment]
Alrighty, should be fixed now
