### ISSUE TITLE
Bungee errors at startup

### ISSUE THREAD

**Issue by egg82** [egg82/AltFinder#6]
While harmless, Bungee throws a fit at startup with the plugin load that looks very ugly; related to logback and the GameAnalytics class not having the required deps in the uber jar. Should fix that.

**Comment by Cosido** [comment]
Having startup errors that seem harmless on the newest update (3.4.23),  side note, AntiVPN gives the same errors, I have them in a single log here, can report to AntiVPN hub as well if youd like, wondering if it is to do with this same issue

https://gist.github.com/Cosido/881f848b6fbfac8875201555b03163c3

**Comment by egg82** [comment]
It's a similar-ish issue, though I should fix my logbcak implementation at some point it's not a super high priority. Having the output there is a bit nasty though.

**Comment by egg82** [comment]
Fixed in a92a124
